metricbeat.modules:
- module: system
  metricsets:
    - cpu
    - filesystem
    - memory
    - network
    - process
  enabled: true
  period: 10s
  processes: ['.*']
  cpu_ticks: false

output.elasticsearch:
  hosts: "192.168.10.66:9200"

setup.kibana:
  host: "192.168.10.66:5601"
