heartbeat.monitors:
- type: icmp
  schedule: '*/5 * * * * * *'
  hosts: 
    - "192.168.10.66"
    - "192.168.10.61"
  mode: all

- type: tcp
  schedule: '@every 5s'
  hosts: 
    - "192.168.10.66:22"
    - "192.168.10.61:22"  # default TCP Echo Protocol
  check.send: "Check"
  check.receive: "Check"
  mode: all

- type: http
  schedule: '@every 5s'
  urls: 
    - "http://foobar.com:80/"
    - "http://google.fi:80/"
    - "http://cgi.fi:80"
  check.response.status: 200
heartbeat.scheduler:
  limit: 10

output.elasticsearch:
  hosts: ["http://192.168.10.66:9200"]


setup.kibana.host: "192.168.10.66:5601"
setup.dashboards.enabled: true

